### ISSUE TITLE
Align not aligning to assignment operator.

### ISSUE THREAD

**Issue by ctrl-alt-adrian** [bsarrazin/soothe#1] opened 2017-01-04 17:18 UTC
When in a function I can't get all of the assignment operators "=" to align perfectly as demonstrated in the Soothe video.  

Here is the code I'm using:

```swift
func updateMainUI() {
        dateLbl.text = currentWeather.date
        // Gotta convert currentWeather.currrentTemp to a string since UILable espect a string and not a double.
        currentTempLbl.text = "\(currentWeather.currentTemp)"
        currentWeatherTypeLbl.text = currentWeather.weatherType
        locationLbl.text = currentWeather.cityName
        currentWeatherImg.image = UIImage(named: currentWeather.weatherType)
    }
```

Here is a video of what happens. 

![Aligning issue](http://i.imgur.com/MAnOsd8.gif)

**Comment by bsrz** [comment] 2017-01-14 13:35
@adriandeveloper I've been trying to reproduce your issue from memory (I can't see your video). Everything seems to be working fine for me. Check this GIF:

![screenflow](https://cloud.githubusercontent.com/assets/1077441/21955222/5668098c-da34-11e6-8dc0-fb63c0e61b15.gif)

Are you able to reproduce the issue consistently?

**Comment by ctrl-alt-adrian** [comment] 2017-01-20 12:19
It's working now.  Was this updated recently?

**Comment by bsrz** [comment] 2017-01-20 13:17
@adriandeveloper nothing was updated. I will close this issue but if you ever find reproducible steps, please let me know.

**Closed as completed by bsrz** 2017-01-20 13:17 UTC
